# This workflow build and publish the docker image to the GitHub Container Registry for x86_64 and aarch64 arch

name: Docker Image CI

on:
  push:
    branches:
      - "master"
  # Run workflow weekly
  schedule:
    - cron: "0 0 * * 0"

# Limit the concurrency of this workflow to one job
concurrency:
  group: docker
  cancel-in-progress: true


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: simophin/certbot-dns-cloudflare:latest